# Site
repository: ahmadateya/ahmadateya.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ahmad Ateya
title: Software Engineer
email: ahmad.m.ateya@gmail.com
phone: 01150326768
#website: ahmadateya.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ahmadateya
linkedin_username: ahmadateya
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Pdf Download
    icon: far fa-file-pdf
    url: #
  - title: Send mail to ahmad.m.ateya@gmail.com
    icon: fas fa-envelope
    url: mailto:ahmad.m.ateya@gmail.com
  - title: Hackerrank
    icon: fab fa-hackerrank
    url: #


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ahmad Ateya a Software Engineer with +2 Years of Experience, Most of time I am in the Backend, DevOps, and Cloud.

   I am most intersted in: <mark>AWS</mark>, <mark>Web3</mark>, and <mark>Cloud Native Apps</mark>

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Our Education
        link: https://our-education.net/
        link_text: our-education.net
        sub_title: Software Engineer
        caption: >
          October 2021 - Present (Part-time)
          June 2020 - October 2021 (Full-time)
        quote: >
          the tech branch to an existed schooling company located in Saudi Arabia, making the needed digital transformation.
        description: | # this will include new lines to allow paragraphs
          Collected a lot of experience in dealing with big structures (very near to microservices structures). Having a chance to enter the DevOps area and getting a hands-on experience <mark>AWS</mark> and <mark>k8s</mark>, and <mark>Terraform</mark> besides my primary work as a Backend Developer.

      - layout: left
        title: Kite Agency
        link: https://www.kite.agency/
        link_text: kite.agency
        sub_title: Backend Developer
        caption: >
          October 2019 - May 2020 (Full-time)
          June 2019 - September 2019 (Internship)
        quote: Software House.
        description: | # this will include new lines to allow paragraphs
          First got an internship for 3 months and then joined the backend team participated in building projects like [Ta3lom](https://ta3lom.com/ar/).

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
      - title: Ta3lom
        link: https://github.com/Haki-Malai/sudoku-smart-solver
        link_text: Project Website
        additional_links:
          - title:  Haki-Malai/sudoku-smart-solver
            icon: fab fa-github
            url: github.com/Haki-Malai/sudoku-smart-solver
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Solving sudokus is a complex mathematics problem
        description: | # this will include new lines to allow paragraphs
          This project was done with the purpose of me learning some react-js, php and java. Te a sudoku solver was chosen from me because it may sound simple but in reality if someone has or wants to be able to solve a sudoku really fast it is necessery to use double-linked lists as with backtracking very often it is needed a big number of recursions for the solution of the problem. Also, it is necessery to have a server that solver the problem as JavaScript has a limit on recursions that can occur, even if double linked lists will be used. This use of linked lists is called "Dancing Links".

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Al-Azhar University
        caption: Graduating in 2022
        sub_title: Computer Engineering
        description: I spent a lot of my free time as a committee member of the <mark>AZEC</mark> taking on roles such as *Technical Instructor* and *Projects Mentor*.

      - layout: left
          title: Self-taught
          caption: all the time
          sub_title: Computer Engineering
          quote: I am a strong believer in the Self-study learning method.

  - title: Skills & Technologies
    layout: skills
    content:
      - title: Backend Development Laravel-PHP / Mysql / Postgresql
        level: 8
      - title: Golang / Linux / SQL / Git
        level: 7
      - title: DevOps & Deployment Docker / Nginx
        level: 5
      - title: Cloud & Infrastructure AWS / Terraform / k8s
        level: 4
      - title: Other Technolgies WordPress / VueJS / NuxtJS
        level: no-level

# Footer
footer_show_references: false

# Build settings
remote_theme: ahmadateya/ahmadateya.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
